### ISSUE TITLE
[JOSS Review]: Usage example

### ISSUE THREAD

**Issue by CFGrote** [Jacks0nJ/PyFPT#34]
Re  [JOSS #4509](https://github.com/openjournals/joss-reviews/issues/4509)

## Tutorial notebook

The documentation at  https://pyfpt.readthedocs.io/en/latest/Installing%20and%20First%20Simulation.html sources the User guide notebooks in
`User guides/`. I found no issue going through them.

 A minor source of confusion may arise from the additional (redundant?) notebooks in `docs/source`, which look identical but miss some
local dependencies (e.g. the mpl_style.py module). Maybe they can be removed?

**Comment by Jacks0nJ** [comment]
I agree this could lead to confusion. The reason they are duplicated is the user guides in docs/source are used to generate html pages for the documentation, so the user guides can also be viewed again there. It was easier to simply duplicate them where the ReadTheDocs pages are generated. I'm more than happy to implement a more elegant solution if you have suggestion.

**Comment by Jacks0nJ** [comment]
@CFGrote I'll look into it. I'm currently away from my linux machine, but will try to implement it once I'm back.

**Comment by Jacks0nJ** [comment]
I've used the [nbsphinx-link](https://github.com/vidartf/nbsphinx-link) to allow the documentation read directly from the guides folder. It seems wanting to add Jupyter notebooks to the documentation from a guides folder is a common problem!

So the duplication should hopefully be fixed.

**Comment by CFGrote** [comment]
Perfect!
