### ISSUE TITLE
Error in User Guide 1

### ISSUE THREAD

**Issue by geraintpalmer** [Jacks0nJ/PyFPT#44]
HI @Jacks0nJ I am one of the reviewers for the JOSS paper.

Working through User Guide 1 (https://pyfpt.readthedocs.io/en/latest/User_guide1.html), the following raises an error:

```
>>> gaussian_pdf = fpt.analytics.gaussian_pdf(V, V_dif, V_ddif, phi_in, phi_end)
>>> plt.errorbar(bin_centres, heights, yerr=errors, fmt=".", ms=7,
...              label='{0}'.format(r'Importance Sample'))
>>> plt.plot(bin_centres, gaussian_pdf(bin_centres),
...          label='{0}'.format('Gaussian'), color='k')
>>> # Need to use log scale to see data in the far tail
>>> plt.yscale('log')
>>> plt.xlabel(r'$\mathcal{N}$')
>>> plt.ylabel(r'$P(\mathcal{N})$')
>>> plt.legend()
```

Similarly with the Edgeworth series.

This is because the following doesn't work as `bin_centres` is a list:

```
>>> gaussian_pdf(bin_centres)
```

This is fixed by:

```
>>> [gaussian_pdf(b) for b in bin_centres]
```

or by:

```
>>> import numpy as np
>>> gaussian_pdf(np.array(bin_centres))
```

**Comment by Jacks0nJ** [comment]
Hi @geraintpalmer,
Thanks for going though it. 
I'll update the guides to fix this mistake soon (I must have changed to numpy arrays but accidently deleted that cell).

**Comment by Jacks0nJ** [comment]
Hi @geraintpalmer
Apologies but I'm struggling to reproduce this error, as while `bin_centres` is a list, it is converted to a numpy array in cell 7, just below where the [list is generated](https://pyfpt.readthedocs.io/en/latest/User_guide1.html). This conversion to numpy arrays is not done in the "multi-dimensional" branch, but please ignore this branch as it is a work in progress. 

Please do let me know if the error persists.

**Comment by geraintpalmer** [comment]
Sorry, I don't know how I missed half that cell when working through the tutorial!

Thanks for the reply :)
